services:
  client:
    build:
      context: .
      dockerfile: ./apps/client/Dockerfile
    networks:
      - hangmen
    environment:
      - URL=https://api.hangmen.builtbykadeem.com
    expose:
      - 8080
  server:
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
    networks:
      - hangmen
    environment:
      - CLIENT_URL=https://hangmen.builtbykadeem.com
      - PORT=3001
    expose:
      - 3001
networks:
  hangmen:
